realsense:
  single:
    depth_camera_serial: CHANGE_ME
  multi:
    left_depth_camera_serial: CHANGE_ME
    right_depth_camera_serial: CHANGE_ME

usb_kernels:
  multi_sensor:
    left_serial:   1-4.4:1.0
    right_serial:  1-3.4:1.0
    left_fisheye:  1-4.3:1.0
    right_fisheye: 1-3.3:1.0

  multi_gripper:
    left_serial:   1-2.2.4:1.0
    right_serial:  1-2.1.4:1.0
    left_fisheye:  1-2.2.3:1.0
    right_fisheye: 1-2.1.3:1.0

  sensor_gripper:
    sensor_serial:   1-4.4:1.0
    gripper_serial:  1-2.4:1.0
    sensor_fisheye:  1-4.3:1.0
    gripper_fisheye: 1-2.3:1.0
